### ISSUE TITLE
Dropping logrus for std log

### ISSUE THREAD

**Issue by atakanyenel** [chhabraamit/2048#4]
I see that you have only 3 log statements in your code and they are very trivial to write with the std log. Would you think about dropping sirupsen/logrus, so that you will have less indirect dependencies and smaller binary size ?

**Comment by chhabraamit** [comment]
Fair enough. I used them just like that. With each side project, I want to try different things. And used `logrus` with that spirit.

**Comment by chhabraamit** [comment]
Removed the dependency on `logrus`. Thanks for showing interest in the project.
